"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, Compass, Copy, Dice5, Flame, Heart, HelpCircle, Hourglass, LoaderCircle, MessageCircle, Moon, Plus, ScrollText, Send, Shield, Sparkles, Swords, Tent, Users, X, KeyRound } from "lucide-react";
import { ABILITIES, abilityMod, CLASSES, skillMod, SKILLS } from "@/lib/game/characters";
import type { Ability, HeroClass, Message, View } from "@/lib/game/types";
import type { Command } from "@/lib/game/engine";
import { Avatar, classIcon, RuleContent, sign, Transcript } from "./components";
import { api, type Bootstrap, type ToolContext, registerTools } from "./client";
import "../table.css";

type Section = "lobby" | "characters" | "camp" | "rules" | "adventure";
export default function Home() {
  const [data, setData] = useState<Bootstrap | null>(null), [section, setSection] = useState<Section>("lobby");
  const [view, setView] = useState<View | null>(null), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true);
  const [error, setError] = useState(""), [notice, setNotice] = useState(""), [text, setText] = useState("");
  const [modal, setModal] = useState<"adventure" | "hero" | "join" | null>(null), [help, setHelp] = useState(false);
  const [campaignId, setCampaignId] = useState("silent-bell"), [classId, setClassId] = useState<HeroClass>("fighter");
  const [name, setName] = useState("星桥"), [background, setBackground] = useState(""), [heroId, setHeroId] = useState("");
  const [mode, setMode] = useState<"solo" | "party">("solo"), [roomCode, setRoomCode] = useState("");
  const [campHeroId, setCampHeroId] = useState(""), [campMessages, setCampMessages] = useState<Message[]>([]);
  const [proposal, setProposal] = useState<string | null>(null), [rolling, setRolling] = useState(false);
  const operating = useRef(false), failedRequest = useRef<{key: string; id: string} | null>(null);
  const refresh = useCallback(async () => {const result = await api<Bootstrap>(); setData(result); return result;}, []);
  useEffect(() => {api<Bootstrap>().then(async result => {
    setData(result);
    setCampHeroId(result.heroes[0]?.id || ""); const id = new URLSearchParams(location.search).get("adventure");
    if (id && result.games.some(g => g.id === id)) {const r = await api<{view: View}>(undefined, `?id=${id}`); setView(r.view); setSection("adventure");}
  }).catch(e => setError(e.message)).finally(() => setLoading(false));}, []);
  useEffect(() => {if (!campHeroId) return; let active = true;
    api<{messages: Message[]}>(undefined, `?camp=${campHeroId}`).then(r => {if (active) setCampMessages(r.messages);}).catch(e => setError(e.message));
    return () => {active = false;};
  }, [campHeroId]);
  const activeGameId = view?.game.id, activeGameMode = view?.game.mode, activeGameStatus = view?.game.status;
  useEffect(() => {window.scrollTo({top: 0, behavior: "instant"});}, [section, activeGameId]);
  useEffect(() => {if (!activeGameId || activeGameMode !== "party" || activeGameStatus === "complete") return;
    const timer = setInterval(async () => {if (operating.current) return; try {const r = await api<{view: View}>(undefined, `?id=${activeGameId}`); setView(p => p && r.view.version > p.version ? r.view : p);} catch { /* Explicit actions report connection failures. */ }}, 3500);
    return () => clearInterval(timer);
  }, [activeGameId, activeGameMode, activeGameStatus]);
  const run = useCallback(async <T,>(task: () => Promise<T>): Promise<T | undefined> => {
    if (operating.current) return; operating.current = true; setBusy(true); setError(""); setNotice("");
    try {return await task();} catch (e) {setError(e instanceof Error ? e.message : "暂时无法完成操作。");}
    finally {operating.current = false; setBusy(false); setRolling(false);}
  }, []);
  const enter = useCallback(async (id: string) => {const r = await api<{view: View}>(undefined, `?id=${id}`); setView(r.view); setSection("adventure"); setProposal(null); setText(""); history.replaceState(null, "", `?adventure=${id}`); return {id, status: r.view.game.status};}, []);
  const command = useCallback(async (action: Command) => {
    if (!view) throw new Error("请先进入冒险。");
    return run(async () => {const key = JSON.stringify({id: view.game.id, action}); const requestId = failedRequest.current?.key === key ? failedRequest.current.id : crypto.randomUUID(); failedRequest.current = {key, id: requestId};
      if (["roll", "attack"].includes(action.kind)) setRolling(true);
      const r = await api<{view: View; aiNotice?: string}>({op: "game.command", id: view.game.id, expectedVersion: view.version, command: action, requestId}); failedRequest.current = null; setView(r.view); setProposal(null);
      if (r.aiNotice) setNotice("规则结果已保存。AI 叙事暂未生成，你可以继续行动。");
      return {id: r.view.game.id, status: r.view.game.status, version: r.view.version};
    });
  }, [view, run]);
  const toolContext = useRef<ToolContext | null>(null);
  useEffect(() => {toolContext.current = {view, data, enter, command};}, [view, data, enter, command]);
  useEffect(() => registerTools(() => toolContext.current!), []);
  function create(selectedCampaign = "silent-bell", characterOnly = false) {setCampaignId(selectedCampaign); setHeroId(characterOnly ? "" : data?.heroes[0]?.id || ""); setModal(characterOnly ? "hero" : "adventure"); setName("星桥"); setBackground(""); setError("");}
  async function saveCreation() {await run(async () => {
    let selected = heroId;
    if (!selected || modal === "hero") {const r = await api<{hero: {id: string}}>({op: "hero.create", classId, name, background}); selected = r.hero.id; setHeroId(selected);}
    if (modal === "hero") {setCampHeroId(selected); setModal(null); await refresh(); setSection("characters"); return;}
    const r = await api<{view: View}>({op: "game.create", heroId: selected, campaignId, mode}); setView(r.view); setModal(null); setSection("adventure"); setText(""); setProposal(null); history.replaceState(null, "", `?adventure=${r.view.game.id}`); await refresh();
  });}
  async function talk(camp = false) {const input = text.trim(); if (!input) return; await run(async () => {
    if (camp) {const r = await api<{messages: Message[]}>({op: "camp.talk", heroId: campHeroId, text: input}); setCampMessages(r.messages);}
    else if (view) {const r = await api<{view: View; proposal?: {actionId: string}}>({op: "game.talk", id: view.game.id, expectedVersion: view.version, requestId: crypto.randomUUID(), text: input}); setView(r.view); setProposal(r.proposal?.actionId || null);}
    setText("");
  });}
  async function join() {await run(async () => {const r = await api<{view: View}>({op: "game.join", heroId, roomCode: roomCode.toUpperCase(), requestId: crypto.randomUUID()}); setView(r.view); setModal(null); setSection("adventure"); history.replaceState(null, "", `?adventure=${r.view.game.id}`); await refresh();});}
  function navigate(next: Section) {setSection(next); setError(""); setText(""); if (next === "lobby") {history.replaceState(null, "", "/"); void refresh().catch(e => setError(e.message));}}
  const game = view?.game, hero = game?.players.find(p => p.userId === data?.userId)?.hero, campHero = data?.heroes.find(h => h.id === campHeroId);
  const currentTurn = game?.combat?.order[game.combat.turn], myTurn = !game?.combat || currentTurn === hero?.id;
  return <div className="table-app"><aside className="sidebar"><Link className="brand" href="/" onClick={e => {e.preventDefault(); navigate("lobby");}}><span className="brand-emblem"><Flame size={26}/></span><span>灯火之下<small>LANTERN TABLE</small></span></Link><div className="sidebar-label">你的冒险桌</div><nav aria-label="主导航">{([{id: "lobby", name: "模组大厅", icon: Compass}, {id: "characters", name: "我的角色", icon: Users}, {id: "camp", name: "营地夜话", icon: Tent}, {id: "rules", name: "新手手册", icon: BookOpen}] as const).map(item => <button key={item.id} className={`nav-item ${section === item.id ? "active" : ""}`} onClick={() => navigate(item.id)}><item.icon size={19}/><span>{item.name}</span>{section === item.id && <span className="nav-dot"/>}</button>)}{view && <button className={`nav-item ${section === "adventure" ? "active" : ""}`} onClick={() => navigate("adventure")}><Dice5 size={19}/><span>当前冒险</span><span className="live-dot"/></button>}</nav><div className="sidebar-bottom"><div className="lantern-note"><Flame size={21}/><p>不必知道所有规则。<br/>带上好奇心就够了。</p></div><div className="account"><span className="account-orb">旅</span><div><strong>旅人</strong><small>你的私人冒险桌</small></div><Moon size={16}/></div></div></aside>
  <div className="main-shell"><header className="topbar"><div className="breadcrumb">冒险桌 <ChevronRight size={13}/><span>{section === "lobby" ? "模组大厅" : section === "characters" ? "我的角色" : section === "camp" ? "营地夜话" : section === "rules" ? "新手手册" : view?.title}</span></div><div className="topbar-right"><span className="status-pill"><span className={data?.aiReady ? "live-dot" : "neutral-dot"}/>{data?.aiReady ? "AI 主持人已连接" : "规则桌已就绪"}</span><button className="icon-button" aria-label="打开新手帮助" onClick={() => setHelp(true)}><HelpCircle size={20}/></button></div></header>
  {(error || notice) && <div className={`alert ${error ? "error" : ""}`} role="alert"><span>{error || notice}</span><button aria-label="关闭提示" onClick={() => {setError(""); setNotice("");}}><X size={17}/></button></div>}
  {loading ? <div className="loading-screen"><Flame size={36}/><h1>正在为你点亮冒险桌…</h1><p>读取角色与云端存档</p><LoaderCircle className="spin" size={22}/></div> : !data ? <div className="empty-state"><Flame/><h1>冒险桌暂未连接</h1><p>{error || "请登录后重试。"}</p><button className="button primary" onClick={() => location.reload()}>重新连接</button></div> : <>
  {section === "lobby" && <main className="lobby page-content"><section className="hero-banner"><div className="hero-shade"/><div className="hero-copy"><span className="hero-kicker"><span/>一盏灯，一场属于你的冒险</span><h1>故事等你。<br/><em>骰子，交给命运。</em></h1><p>走进河谷，成为故事里的人。<br/>一位耐心的 AI 主持人，陪你开始第一场跑团。</p><button className="button primary hero-cta" onClick={() => create()}>开启第一场冒险 <ArrowRight size={18}/></button><div className="hero-tags"><span><Check size={13}/>不需要规则基础</span><span><Check size={13}/>随时离开，自动存档</span></div></div><div className="banner-caption"><span>MOONBRIDGE VALLEY</span>月桥河谷 · 原创冒险世界</div></section>
  <div className="section-heading"><div><p className="eyebrow">CHOOSE YOUR STORY</p><h2>今晚，去哪里？</h2><p>独立短篇。你的选择，会留在结局里。</p></div><button className="text-button" onClick={() => {setHeroId(data.heroes[0]?.id || ""); setRoomCode(""); setModal("join");}}>加入朋友的房间 <Users size={16}/></button></div><div className="campaign-grid">{data.campaigns.map((campaign, index) => <article className={`campaign-card campaign-${index}`} key={campaign.id}><div className="campaign-art"><div className="campaign-art-shade"/><span className="campaign-badge">{index === 0 ? "推荐 · 第一场跑团" : "新的抉择"}</span><span className="chapter-number">0{index + 1}</span><span className="campaign-symbol">{index === 0 ? <Flame size={44}/> : <Compass size={44}/>}</span></div><div className="campaign-info"><div className="campaign-meta"><span>{campaign.theme}</span><span><Hourglass size={13}/>{campaign.minutes}</span></div><h3>{campaign.title}</h3><p>{campaign.description}</p><div className="campaign-bottom"><span><span className="little-dot"/>{campaign.difficulty}</span><button className="button secondary" onClick={() => create(campaign.id)}>选择冒险 <ArrowRight size={15}/></button></div></div></article>)}</div>
  {data.games.length > 0 && <section className="saved-section"><div className="section-heading compact"><div><h2>留下的故事</h2><p>回来时，灯还亮着。</p></div><ScrollText size={22}/></div><div className="saved-list">{data.games.map(saved => <button key={saved.id} className="saved-row" disabled={busy} onClick={() => void run(() => enter(saved.id))}><span className="saved-icon"><ScrollText size={21}/></span><div><strong>{saved.title}</strong><small>{saved.heroNames.join("、")} · {saved.mode === "party" ? "组队" : "单人"} · 第 {saved.scene + 1} 幕</small></div><span className={`saved-status ${saved.status}`}>{saved.status === "complete" ? "已落幕" : saved.status === "waiting" ? "等待队友" : "继续冒险"}</span><ChevronRight size={17}/></button>)}</div></section>}
  <section className="first-steps"><div className="section-heading compact"><div><p className="eyebrow">A LITTLE GUIDANCE</p><h2>你只需要做三件事</h2></div><button className="text-button" onClick={() => navigate("rules")}>翻开新手手册 <ArrowRight size={16}/></button></div><div className="step-grid"><div><span>01</span><h3>成为一个角色</h3><p>选一个一级模板，为旅人取名，想想为何上路。</p></div><div><span>02</span><h3>告诉世界你的想法</h3><p>观察、交谈、尝试。点选行动，也能自由描述。</p></div><div><span>03</span><h3>让骰子带来意外</h3><p>先看规则与代价，再掷骰。成败都让故事继续。</p></div></div></section></main>}
  {section === "characters" && <main className="page-content"><div className="page-heading"><div><p className="eyebrow">THE PEOPLE IN YOUR STORIES</p><h1>我的角色</h1><p>每一位旅人，都带着还没写完的故事。</p></div><button className="button primary" onClick={() => create("silent-bell", true)}><Plus size={17}/>新建角色</button></div>{!data.heroes.length ? <div className="empty-state"><Users size={40}/><h2>从一个名字开始</h2><p>不用填复杂表格。三个一级模板，陪你先走一程。</p><button className="button primary" onClick={() => create("silent-bell", true)}>创建第一位旅人 <ArrowRight size={16}/></button></div> : <div className="character-grid">{data.heroes.map(character => <article className="character-card" key={character.id}><div className="character-card-top"><Avatar hero={character}/><div><span className="eyebrow">LEVEL 01 · 人类</span><h2>{character.name}</h2><p>{CLASSES[character.classId].name} · {CLASSES[character.classId].subtitle}</p></div></div><p className="character-background">{character.background}</p><div className="character-stats"><span><Heart size={15}/>{character.maxHp}<small>生命</small></span><span><Shield size={15}/>{character.ac}<small>护甲</small></span><span><Dice5 size={15}/>+2<small>熟练</small></span></div><p className="feature-text">{CLASSES[character.classId].feature}</p><div className="card-actions"><button className="button secondary" onClick={() => {setCampHeroId(character.id); navigate("camp");}}>去营地聊聊 <MessageCircle size={15}/></button><button className="text-button" onClick={() => {create(); setHeroId(character.id);}}>带他上路 <ArrowRight size={15}/></button></div></article>)}</div>}<p className="subtle-note">角色册保存出发模板。每场冒险独立记录生命和资源，新开一场不会覆盖旧存档。</p></main>}
  {section === "camp" && <main className="page-content"><div className="page-heading"><div><p className="eyebrow">BY THE CAMPFIRE</p><h1>营地夜话</h1><p>冒险之外，也给旅人一点说话的时间。</p></div><Tent size={30}/></div>{!campHero ? <div className="empty-state"><Tent size={40}/><h2>篝火旁还空着一个位置</h2><p>先创建一位角色，再听听他的故事。</p><button className="button primary" onClick={() => create("silent-bell", true)}>创建角色</button></div> : <div className="camp-layout"><aside className="camp-people"><h3>今晚的旅人</h3>{data.heroes.map(character => <button key={character.id} className={`camp-person ${campHeroId === character.id ? "selected" : ""}`} disabled={busy} onClick={() => {setCampHeroId(character.id); setText("");}}><Avatar hero={character} small/><span><strong>{character.name}</strong><small>{CLASSES[character.classId].name}</small></span></button>)}<p>对话云端保存，用于扮演，不改变冒险数值。</p></aside><section className="chat-panel"><div className="chat-heading"><Flame size={19}/><div><strong>{campHero.name}</strong><small>篝火未眠</small></div></div>{campMessages.length ? <Transcript messages={campMessages}/> : <div className="camp-welcome"><Avatar hero={campHero}/><h2>火光映在{campHero.name}的脸上。</h2><p>{campHero.background}</p><div className="prompt-chips">{["你为什么离开家乡？", "第一次冒险，你紧张吗？", "教我怎么扮演你吧。"].map(prompt => <button key={prompt} onClick={() => setText(prompt)}>{prompt}</button>)}</div></div>}<form className="composer" onSubmit={e => {e.preventDefault(); void talk(true);}}><input aria-label="营地对话" placeholder="问问他的故事，或聊聊你的想法…" maxLength={700} value={text} disabled={busy} onChange={e => setText(e.target.value)}/><button aria-label="发送营地消息" className="send-button" disabled={busy || !text.trim()}>{busy ? <LoaderCircle className="spin" size={18}/> : <Send size={18}/>}</button></form></section></div>}</main>}
  {section === "rules" && <main className="page-content rules-page"><div className="manual-art"><BookOpen size={46}/><span>THE TRAVELER’S HANDBOOK</span></div><RuleContent/></main>}
  {section === "adventure" && view && game && <main className="adventure-page"><div className="adventure-heading"><button className="icon-button" aria-label="返回大厅" onClick={() => navigate("lobby")}><ArrowLeft size={19}/></button><div><span className="eyebrow">{game.mode === "solo" ? "SOLO" : "PARTY"} ADVENTURE · 第 {game.scene + 1} / {view.sceneCount} 幕</span><h1>{view.title}</h1></div><div className="danger-meter" title="失败与延误增加危险，达到 4 影响结局"><span><Hourglass size={14}/>危险 {game.danger}/6</span><div>{Array.from({length: 6}, (_, i) => <i className={i < game.danger ? "filled" : ""} key={i}/>)}</div></div><button className="text-button desktop-only" onClick={() => setHelp(true)}><BookOpen size={16}/>规则</button></div>
  <div className="adventure-layout"><section className="adventure-main"><div className="scene-card"><div className="scene-number">0{game.scene + 1}</div><div><span className="eyebrow">CURRENT SCENE</span><h2>{view.scene.title}</h2><p>{view.scene.description}</p></div></div>
  {game.status === "waiting" && <div className="waiting-card"><Users size={32}/><h2>灯已点亮，等大家落座</h2><p>最多 4 位玩家。队友需要有网站访问权限，并用自己的 ChatGPT 账户进入。</p><button className="room-code" onClick={() => {void navigator.clipboard.writeText(game.roomCode).then(() => setNotice("邀请码已复制。")).catch(() => setNotice(`邀请码：${game.roomCode}`));}}>{game.roomCode}<Copy size={18}/></button><p>{game.players.map(p => p.hero.name).join("、")} 已就位</p>{game.owner === data.userId ? <button className="button primary" disabled={busy} onClick={() => void command({kind: "start"})}>开始冒险 <ArrowRight size={16}/></button> : <span className="status-pill">等待房主开始</span>}</div>}
  {game.status === "complete" && view.ending && <div className="ending-card"><span className="ending-mark">✦</span><span className="eyebrow">A STORY TO REMEMBER</span><h2>{view.ending.title}</h2><p>{view.ending.text}</p><div className="ending-details"><span>{game.turns} 次行动</span><span>{view.clues.length} 条线索</span><span>危险 {game.danger}/6</span></div><button className="button primary" onClick={() => navigate("lobby")}>带着故事回到大厅 <ArrowRight size={16}/></button></div>}
  <div className="journal-heading"><span><ScrollText size={17}/>冒险记录</span><span>已自动保存至云端</span></div><Transcript messages={game.messages}/>
  {game.status === "active" && <><div className="action-area">{game.pending ? <div className="pending-card"><div className="pending-header"><span className={`die-face ${rolling ? "rolling" : ""}`}><Dice5 size={36}/></span><div><span className="eyebrow">THE DICE HAVE A SAY</span><h3>{game.pending.title}</h3><p>{SKILLS[game.pending.skill].name}检定</p></div></div><div className="check-values"><span><small>难度 DC</small><strong>{game.pending.dc}</strong></span><span><small>你的加值</small><strong>{sign(game.pending.modifier)}</strong></span><span><small>掷骰方式</small><strong>{game.pending.advantage ? "优势 · 取高" : "1d20"}</strong></span></div><p className="stakes"><strong>失败代价：</strong>{game.pending.consequence}危险刻度 +1。</p><button className="button primary roll-button" disabled={busy || game.pending.actorId !== hero?.id} onClick={() => void command({kind: "roll"})}>{busy ? <LoaderCircle className="spin" size={18}/> : <Dice5 size={19}/>} {game.pending.actorId !== hero?.id ? "等待队友掷骰" : busy ? "骰子正在落定…" : "确认代价，掷出骰子"}</button></div> : game.combat ? <div className="combat-card"><div className="combat-heading"><Swords size={21}/><strong>第 {game.combat.round} 回合</strong><span>轮到 {game.players.find(p => p.hero.id === currentTurn)?.hero.name || "对手"}</span></div><div className="enemy-row"><span className="enemy-symbol">☾</span><div><strong>{game.combat.enemy.name}</strong><div className="hp-track"><i style={{width: `${game.combat.enemy.hp / game.combat.enemy.maxHp * 100}%`}}/></div></div><span>{game.combat.enemy.hp}/{game.combat.enemy.maxHp} HP<small>AC {game.combat.enemy.ac}</small></span></div><div className="combat-actions"><button className="button primary" disabled={busy || !myTurn} onClick={() => void command({kind: "attack"})}>{hero && classIcon(hero.classId, 17)}{hero ? CLASSES[hero.classId].weapon : "攻击"}攻击</button><button className="button secondary" disabled={busy || !myTurn} onClick={() => void command({kind: "dodge"})}><Shield size={16}/>闪避一回合</button>{hero?.classId === "wizard" && <button className="button secondary" disabled={busy || !myTurn || !hero.spellSlots} onClick={() => void command({kind: "missile"})}><Sparkles size={16}/>魔法飞弹 · 1 法术位</button>}</div><p className="subtle-note">每回合一个主要动作。攻击骰由服务器掷出，不满意不能重掷。</p></div> : <><div className="action-heading"><span>你打算怎么做？</span><small>选择行动，或自由表达</small></div><div className="action-grid">{view.actions.map(action => <button className={`action-option ${action.kind === "combat" ? "risky" : ""}`} key={action.id} disabled={busy} onClick={() => void command({kind: "action", actionId: action.id})}><div className="action-option-top"><strong>{action.title}</strong>{action.kind === "combat" ? <Swords size={16}/> : action.skill ? <Dice5 size={16}/> : <ArrowRight size={16}/>}</div><p>{action.description}</p><span>{action.kind === "combat" ? "战斗 · 先攻决定顺序" : action.skill ? `${SKILLS[action.skill].name} · DC ${action.dc}` : "确定可行 · 无需掷骰"}</span></button>)}</div></>}</div>
  {proposal && <div className="proposal-card"><Sparkles size={17}/><div><strong>主持人的行动建议</strong><p>{view.actions.find(a => a.id === proposal)?.title || "建议已不适用于当前场景"}</p></div><button className="button secondary" disabled={busy || !view.actions.some(a => a.id === proposal)} onClick={() => void command({kind: "action", actionId: proposal})}>采用建议</button><button className="icon-button" aria-label="取消建议" onClick={() => setProposal(null)}><X size={16}/></button></div>}
  <form className="composer" onSubmit={e => {e.preventDefault(); void talk();}}><input aria-label="对主持人说" placeholder="“我想先问问他…” 用自己的话行动或提问" value={text} maxLength={700} disabled={busy} onChange={e => setText(e.target.value)}/><button className="send-button" aria-label="发送给主持人" disabled={busy || !text.trim()}>{busy ? <LoaderCircle className="spin" size={18}/> : <Send size={18}/>}</button></form><p className="composer-note">{busy ? "主持人正在回应，规则结果会先保存。" : "AI 理解意图，行动建议需要你确认。"}</p></>}
  </section><aside className="adventure-side">{hero && <section className="hero-sheet"><div className="sheet-heading"><Avatar hero={hero} small/><div><h3>{hero.name}</h3><p>一级 · {CLASSES[hero.classId].name}</p></div><Shield size={17}/><span>{hero.ac}</span></div><div className="hp-heading"><span><Heart size={14}/>生命</span><strong>{hero.hp} <small>/ {hero.maxHp}</small></strong></div><div className="hp-track"><i style={{width: `${hero.hp / hero.maxHp * 100}%`}}/></div><div className="ability-grid">{Object.entries(hero.abilities).map(([key, value]) => <div key={key}><small>{ABILITIES[key as Ability]}</small><strong>{sign(abilityMod(value))}</strong><span>{value}</span></div>)}</div><h4>熟练技能</h4><div className="skill-list">{hero.skills.map(skill => <span key={skill}>{SKILLS[skill].name}<strong>{sign(skillMod(hero, skill))}</strong></span>)}</div><div className="resource-list"><span>治疗药水<strong>{hero.potions} 瓶</strong></span><span>生命骰<strong>{hero.hitDice} 枚</strong></span>{hero.classId === "fighter" && <span>复苏之风<strong>{hero.secondWind} 次</strong></span>}{hero.classId === "wizard" && <span>一环法术位<strong>{hero.spellSlots} / 2</strong></span>}</div>{game.status === "active" && <div className="resource-actions"><button disabled={busy || !myTurn || !!game.pending || !hero.potions || hero.hp === hero.maxHp} onClick={() => void command({kind: "potion"})}>饮用治疗药水 <Heart size={14}/></button>{hero.classId === "fighter" && <button disabled={busy || !myTurn || !!game.pending || !hero.secondWind || hero.hp === hero.maxHp} onClick={() => void command({kind: "wind"})}>复苏之风 · 附赠动作 <Sparkles size={14}/></button>}<button disabled={busy || !!game.pending || !!game.combat || !view.scene.safeRest || game.lastRestScene === game.scene || !game.players.some(p => (p.hero.hitDice > 0 && p.hero.hp < p.hero.maxHp) || (p.hero.classId === "fighter" && p.hero.secondWind === 0))} onClick={() => void command({kind: "rest"})}>安全短休 · 1 小时 <Moon size={14}/></button></div>}</section>}
  {game.mode === "party" && <section className="side-card"><h3><Users size={17}/>队伍 · {game.roomCode}</h3>{game.players.map(p => <div className="party-row" key={p.userId}><span>{p.hero.name}{p.userId === game.owner ? " · 房主" : ""}</span><strong>{p.hero.hp}/{p.hero.maxHp}</strong></div>)}</section>}<section className="side-card clues-card"><h3><KeyRound size={17}/>线索袋 <span>{view.clues.length}</span></h3>{view.clues.length ? view.clues.map(clue => <div className="clue" key={clue.title}><span>✦</span><div><strong>{clue.title}</strong><p>{clue.text}</p></div></div>) : <p className="empty-clues">认真倾听和观察，世界会给你线索。</p>}</section><section className="side-card table-reminder"><Flame size={19}/><p>失败不是句号。<br/>也许只是另一条路的开头。</p><button className="text-button" onClick={() => setHelp(true)}>这次用到了什么规则？ <ArrowRight size={14}/></button></section>{game.status === "active" && game.owner === data.userId && <details className="retreat-details"><summary>提前结束冒险</summary><p>返回安全地点，保存撤退结局。这场存档会结束，可以另开一次。</p><button className="button secondary" disabled={busy} onClick={() => void command({kind: "retreat"})}>确认撤退</button></details>}</aside></div></main>}
  </>}
  <footer className="app-footer"><span>✦ 灯火之下 · 原创故事，透明骰子</span><button onClick={() => navigate("rules")}>SRD 5.1 教学子集 · CC BY 4.0</button></footer></div>
  {modal && <div className="modal-backdrop" onClick={e => {if (e.target === e.currentTarget && !busy) setModal(null);}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close icon-button" aria-label="关闭" disabled={busy} onClick={() => setModal(null)}><X size={20}/></button><p className="eyebrow">MAKE YOUR FIRST CHOICE</p><h2 id="modal-title">{modal === "join" ? "一起坐到冒险桌前" : modal === "hero" ? "给故事一个主角" : "把你的名字，写进故事"}</h2><p className="modal-intro">{modal === "adventure" ? data?.campaigns.find(c => c.id === campaignId)?.subtitle : modal === "join" ? "选择角色，输入房主给你的六位邀请码。" : "角色卡已准备好。你来决定他是谁。"}</p>
  {modal !== "hero" && (data?.heroes.length ? <label className="field">出发的角色<select value={heroId} disabled={busy} onChange={e => setHeroId(e.target.value)}><option value="">创建新角色</option>{data.heroes.map(h => <option value={h.id} key={h.id}>{h.name} · {CLASSES[h.classId].name}</option>)}</select></label> : modal === "join" ? <p className="scope-note">请先在「我的角色」创建旅人。</p> : null)}
  {modal === "join" ? <><label className="field">房间邀请码<input value={roomCode} maxLength={6} autoComplete="off" spellCheck={false} onChange={e => setRoomCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g, ""))} placeholder="例如 AB3D7K"/></label><button className="button primary modal-submit" disabled={busy || !heroId || roomCode.length !== 6} onClick={() => void join()}>{busy ? <LoaderCircle className="spin" size={18}/> : <Users size={18}/>}加入房间</button><p className="subtle-note">邀请码用于加入队伍，不授予网站访问权限。目前网站仅你可访问。</p></> : <>
  {(!heroId || modal === "hero") && <><div className="class-picker">{(Object.keys(CLASSES) as HeroClass[]).map(id => <button key={id} className={`class-choice ${id} ${classId === id ? "selected" : ""}`} onClick={() => setClassId(id)} disabled={busy}>{classIcon(id, 26)}<strong>{CLASSES[id].name}</strong><small>{id === "fighter" ? "稳健 · 好上手" : id === "rogue" ? "灵巧 · 擅长调查" : "知识 · 法术"}</small>{classId === id && <Check size={13} className="class-check"/>}</button>)}</div><div className="chosen-feature"><Sparkles size={15}/>{CLASSES[classId].feature}</div><label className="field">旅人的名字<input value={name} onChange={e => setName(e.target.value)} maxLength={24} disabled={busy} placeholder="你希望大家怎么称呼你？"/></label><label className="field">为什么上路？ <span>选填</span><textarea value={background} onChange={e => setBackground(e.target.value)} maxLength={600} rows={2} disabled={busy} placeholder="例如：替家乡送一封信，途中遇见了冒险。"/></label></>}
  {modal === "adventure" && <div className="mode-picker"><button disabled={busy} className={mode === "solo" ? "selected" : ""} onClick={() => setMode("solo")}><Moon size={16}/><span>独自上路<small>随时开始，适合第一次</small></span></button><button disabled={busy} className={mode === "party" ? "selected" : ""} onClick={() => setMode("party")}><Users size={16}/><span>创建组队房间<small>最多 4 人，共享故事与存档</small></span></button></div>}{error && <p className="form-error" role="alert">{error}</p>}<button className="button primary modal-submit" disabled={busy || (!heroId && !name.trim())} onClick={() => void saveCreation()}>{busy ? <LoaderCircle className="spin" size={18}/> : modal === "hero" ? <Check size={18}/> : <ArrowRight size={18}/>} {modal === "hero" ? "保存角色" : mode === "solo" ? "准备好了，出发" : "创建冒险房间"}</button><p className="subtle-note">一级角色 · 新手救援模式 · 自动存档</p></>}
  </section></div>}
  {help && <div className="drawer-backdrop" onClick={e => {if (e.target === e.currentTarget) setHelp(false);}}><aside className="help-drawer" role="dialog" aria-modal="true" aria-label="新手手册"><button className="icon-button drawer-close" aria-label="关闭手册" onClick={() => setHelp(false)}><X size={21}/></button><RuleContent/></aside></div>}
  </div>;
}

